---
# Prerequisites and setup for tests
- hosts: all

  roles:
  - role: openmicroscopy.docker

  tasks:

  - name: Install iproute
    become: yes
    yum:
      name: iproute
      state: present

  - name: Create notebook directory for users
    become: yes
    file:
      path: /notebooks
      owner: 1000
      state: directory


- hosts: all

  roles:
  - role: ansible-role-idr-jupyter
    idr_jupyter_prefix: /jupyter
    idr_jupyter_notebook_volumes: "{ '/notebooks': '/notebooks' }"
    idr_jupyter_authenticator: dummyauthenticator.DummyAuthenticator
    idr_jupyter_additional_config:
      DummyAuthenticator.password: ome
    idr_jupyter_users: [user]

  # Setup a port-forward to 8000 and you should be able to login with
  # any username, password:ome
