---
# Normal Docker: start and enable the jupyterhub service

- name: jupyterhub | create systemd service
  become: yes
  template:
    src: jupyterhub-docker.j2
    dest: /etc/systemd/system/docker-jupyterhub.service
  notify:
  - reload systemd
  - restart jupyterhub

- name: jupyterhub | enable jupyterhub
  become: yes
  service:
    enabled: "yes"
    name: docker-jupyterhub.service
    state: started
