---
# tasks file for roles/docker-jupyterhub

- name: jupyterhub | check variables
  fail:
    msg: "Invalid value of idr_jupyter_authenticator: {{ idr_jupyter_authenticator }}"
  when: "idr_jupyter_authenticator not in ['system', 'github']"

# This will be used to pass the config file into the server, and for the
# server to store persistent state
- name: jupyterhub | create jupyter working directory
  become: yes
  file:
    path: /srv/jupyterhub
    state: directory

- name: jupyterhub | copy jupyter configuration file
  become: yes
  template:
    src: jupyterhub_config-py.j2
    dest: /srv/jupyterhub/jupyterhub_config.py
  register: jupyterconfig
  notify:
  - restart jupyterhub

- name: jupyterhub | pull images
  become: yes
  docker_image:
    name: "{{ item }}"
    state: "present"
    force: "{{ idr_jupyter_pull_latest }}"
  with_items:
  - "{{ idr_jupyter_hub_image }}"
  - "{{ idr_jupyter_notebook_image }}"

- include: docker.yml
  when: not idr_jupyter_docker_swarm

- include: docker.yml
  when: idr_jupyter_docker_swarm
