---
# tasks file for idr-jupyter

- name: jupyterhub | check variables
  fail:
    msg: "Invalid value of idr_jupyter_authenticator: {{ idr_jupyter_authenticator }}"
  when: "idr_jupyter_authenticator not in ['system', 'github']"

- name: jupyterhub | create jupyter directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /etc/jupyterhub
  - /var/jupyterhub

- name: jupyterhub | install epel repo
  become: yes
  yum:
    name: epel-release
    state: present

# There's a bug in the distro virtualenv package which prevents python3
# virtualenvs being created

- name: jupyterhub | install system dependencies
  become: yes
  yum:
    name:
    - nodejs
    - npm
    # Required by ansible docker_image
    - python-docker-py
    - python34
    state: present

- name: jupyterhub | install node packages
  become: yes
  npm:
    global: yes
    name: configurable-http-proxy
    state: present

- name: jupyterhub | create base directory
  become: yes
  file:
    path: "{{ idr_jupyter_basedir }}"
    state: directory

- name: jupyterhub | download updated virtualenv
  become: yes
  get_url:
    checksum: "sha1:995ce0fa007210ac2f10258999d06813ecdd6eeb"
    dest: "{{ idr_jupyter_basedir }}/virtualenv-15.1.0.tar.gz"
    url: https://pypi.python.org/packages/d4/0c/9840c08189e030873387a73b90ada981885010dd9aea134d6de30cd24cb8/virtualenv-15.1.0.tar.gz

- name: jupyterhub | extract updated virtualenv
  become: yes
  unarchive:
    creates: "{{ idr_jupyter_basedir }}/virtualenv-15.1.0/virtualenv.py"
    dest: "{{ idr_jupyter_basedir }}"
    remote_src: True
    src: "{{ idr_jupyter_basedir }}/virtualenv-15.1.0.tar.gz"

- name: jupyterhub | install python3 packages in virtualenv
  become: yes
  pip:
    name:
    - jupyterhub==0.7.2
    - dockerspawner==0.7.0
    - https://github.com/IDR/oauthenticator/archive/0.5.1-IDR2.zip
    state: present
    virtualenv: "{{ idr_jupyter_basedir }}/venv"
    virtualenv_command: "{{ idr_jupyter_basedir }}/virtualenv-15.1.0/virtualenv.py"
    virtualenv_python: python3

- name: jupyterhub | pull images
  become: yes
  docker_image:
    name: "{{ item }}"
    state: "present"
    force: "{{ idr_jupyter_pull_latest }}"
  with_items:
  - "{{ idr_jupyter_notebook_image }}"

- name: jupyterhub | create systemd service
  become: yes
  template:
    src: systemd-system-jupyterhub-service.j2
    dest: /etc/systemd/system/jupyterhub.service
  notify:
  - reload systemd
  - restart jupyterhub

# This may contain sensitive credentials
- name: jupyterhub | copy jupyter configuration file
  become: yes
  template:
    src: jupyterhub_config-py.j2
    dest: /etc/jupyterhub/jupyterhub_config.py
    owner: root
    group: root
    mode: "0600"
  register: jupyterconfig
  notify:
  - restart jupyterhub

- name: force systemd reload
  meta: flush_handlers

- name: jupyterhub | enable jupyterhub
  become: yes
  service:
    enabled: "yes"
    name: jupyterhub.service
    state: started

#- include: dockerswarm.yml
#  when: idr_jupyter_docker_swarm
